include phocacart to website
btcpayserver/btcpayserver.org pull request #220
Opened 2024-11-29 15:40 UTC by TChukwuleta

Resolve #218 

Cc. @pavlenex

2024-11-29 17:47 UTC, pavlenex commented on transifex/resources/website.json
> +  "grandnode": "Grand Node",
Why?

2024-11-29 17:47 UTC, pavlenex commented on transifex/resources/website.json
> +  "opencart": "Open Cart",
Why?

2024-11-29 17:49 UTC, pavlenex requested changes
tACK, I am just not sure why you changed transifer `resources` we should strive to follow brand design gudelines when mentioning other platforms and avoid interpreting it in our own ways. I am not really sure why you touched `transifex/resources/ ` beyond Phocacart. It potentially breaks translations, did you check that?

2024-11-29 18:20 UTC, TChukwuleta commented
Nah.. I didn't check that.. 

Would revert it

2025-02-07 13:56 UTC, pavlenex approved these changes

2025-02-07 13:57 UTC, merged